version: "3.8"
services:
    app:
        build:
            context: .
        volumes:
            - .:/usr/src/app
            - ../sdk/python/scilog:/usr/local/lib/python3.10/site-packages/scilog
        # infinite loop to keep the container running
        command: /bin/sh -c "while sleep 1000; do :; done"
